import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Header from "./Header";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: "./fonts/gilroy-regular.ttf" });

export const metadata: Metadata = {
  title: "Automatische Angebotserstellung",
  description: "Generated by Benjamin Koubik",
  authors: [{ name: "Benjamin Koubik" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Script src="https://example.com/script.js" />
        <Providers>
          <Header></Header>

          <main className=" dark:bg-black bg-white h-[100vh]  ">
            {children}
          </main>
        </Providers>
        <ToastContainer
          position="top-center"
          theme="dark"
          autoClose={3000}
        ></ToastContainer>
      </body>
    </html>
  );
}
